name: encrypted_messaging
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  encryption:
    path: ./encryption
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter_svg: ^0.22.0
  get_it: ^7.1.3
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  ionicons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/user/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900

    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy/Gilroy-Thin.otf
          weight: 100
        - asset: assets/fonts/Gilroy/Gilroy-UltraLight.otf
          weight: 200
        - asset: assets/fonts/Gilroy/Gilroy-Light.otf
          weight: 300
        - asset: assets/fonts/Gilroy/Gilroy-Regular.otf
          weight: 400
        - asset: assets/fonts/Gilroy/Gilroy-Medium.otf
          weight: 500
        - asset: assets/fonts/Gilroy/Gilroy-Semibold.otf
          weight: 600
        - asset: assets/fonts/Gilroy/Gilroy-Bold.otf
          weight: 700
        - asset: assets/fonts/Gilroy/Gilroy-Extrabold.otf
          weight: 800
        - asset: assets/fonts/Gilroy/Gilroy-Black.otf
          weight: 900
